languageCode: en
languageName: English
languageDirection: ltr
weight: 1
title: peyron.io
params:
  dateFormat: 2006-01-02
  author:
    name: Jacob Peyron
    image: img/me.jpg
    links:
      - email: mailto:jacob@peyron.io
      - github: https://github.com/bdazl
      - x-twitter: https://x.com/jacobpeyron
      - instagram: https://www.instagram.com/jacobpeyron
      - facebook: https://facebook.com/jacob.peyron
      - linkedin: https://linkedin.com/in/jacobpeyron
